### ISSUE TITLE
Provide a way to get "state" in AbstractAuthorizationCodeCallbackServlet::onSuccess()

### ISSUE THREAD

**Issue by emeraldhieu** [google/google-oauth-java-client#102]
You provided AbstractAuthorizationCodeServlet::onAuthorization() to set "state" but didn't provide a way to get it in onSuccess. I think the callback servlet should be like this (or you can pass AuthorizationCodeResponseUrl just like onError).

public abstract class AbstractAuthorizationCodeCallbackServlet extends HttpServlet {

  @Override
  protected final void doGet(HttpServletRequest req, HttpServletResponse resp)
      throws ServletException, IOException {
    StringBuffer buf = req.getRequestURL();
    if (req.getQueryString() != null) {
      buf.append('?').append(req.getQueryString());
    }
    AuthorizationCodeResponseUrl responseUrl = new AuthorizationCodeResponseUrl(buf.toString());
    String code = responseUrl.getCode();

```
// Get "state" here!!!
String state = responseUrl.getState();

if (responseUrl.getError() != null) {
  onError(req, resp, responseUrl);
} else if (code == null) {
  resp.setStatus(HttpServletResponse.SC_BAD_REQUEST);
  resp.getWriter().print("Missing authorization code");
} else {
  lock.lock();
  try {
    if (flow == null) {
      flow = initializeFlow();
    }
    String redirectUri = getRedirectUri(req);
    TokenResponse response = flow.newTokenRequest(code).setRedirectUri(redirectUri).execute();
    String userId = getUserId(req);
    Credential credential = flow.createAndStoreCredential(response, userId);

    // Pass "state" here.
    onSuccess(req, resp, credential, state);
  } finally {
    lock.unlock();
  }
}
```

  }

}

**Comment by fabito** [comment]
I'd rather have a separate callback for checking the state.
I think "onSuccess" is too late. The state check should be performed before initializing the flow.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
