### ISSUE TITLE
getting java.lang.NullPointerException after receiving token response without expires_in

### ISSUE THREAD

**Issue by mico** [google/google-oauth-java-client#104]
I'm getting:

```
java.lang.NullPointerException
    at com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize(AuthorizationCodeInstalledApp.java:71)
```

next time running example, after Credential stored to local file store.
It happens when i'm receiving token response without expires_in.

It crashed at:
credential.getExpiresInSeconds() > 60
in com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize
because expiresInSeconds contains null

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
