### ISSUE TITLE
OAuth token request fails with Dropbox due to scope parameter

### ISSUE THREAD

**Issue by shahamit** [google/google-oauth-java-client#105]
I am trying to use dropbox's api with OAuth authorization. The authorize call fails with an error 
{
  "error" : "invalid_request",
  "error_description" : "unknown field \"scope\""
}

This error is expected because dropbox's token endpoint (https://www.dropbox.com/developers/core/docs#oa2-token) does not expect a scope parameter while it seems google oauth client is passing it internally. Here's how the OAuth call

``` java
        private Credential authorize() throws IOException {
        AuthorizationCodeFlow codeFlow = new AuthorizationCodeFlow.Builder(
                BearerToken.authorizationHeaderAccessMethod(),
                HTTP_TRANSPORT, JSON_FACTORY, new GenericUrl(TOKEN_SERVER_URL),
                new ClientParametersAuthentication(CLIENT_ID, CLIENT_SECRET), CLIENT_ID, AUTHORIZATION_SERVER_URL)
                .build();

        return new AuthorizationCodeInstalledApp(codeFlow, new CustomPromptReceiver()).authorize("user");
    }

    private class CustomPromptReceiver extends AbstractPromptReceiver {

        @Override
        public String getRedirectUri() throws IOException {
            return "https://www.dropbox.com";
        }
    }

I followed the daily motion's sample code while building this sample. Am I missing something basic?
Thanks!
```

**Comment by mikebell90** [comment]
try setting Setscopes(null) - pretty sure that drops it from the uri

**Comment by mattwhisenhunt** [comment]
Looks like your question was answered by a helpful community member. Thanks mikebell90! Please feel free re-open if your question remains unanswered.
