### ISSUE TITLE
Specify different URL for RefreshTokenRequest

### ISSUE THREAD

**Issue by firefoxNX** [google/google-oauth-java-client#107]
The OAuth provider I am connecting to uses a different URL for refreshing token. Is there a way to set different URL for RefreshTokenRequest?

**Comment by wonderfly** [comment]
If you are relying on Credential's auto refreshing, then the best way to achieve this is to extend Credential and override the executeRefreshToken() method. Your subclass would keep a refreshTokenUrl, and a getter that would be called in your executeRefreshToken() implementation.

**Comment by firefoxNX** [comment]
If I extend Credential then I would need to write my own AuthorizationCodeFlow. I am using AuthorizationCodeFlow.createAndStoreCredential() which calls newCredential() which uses Credential.Builder. 

Similar to tokenServerEncodedUrl, authorizationServerEncodedUrl in AuthorizationCodeFlow, can a new member variable be provided to set refreshTokenUrl? This would also need to be exposed from AuthorizationCodeFlow.Builder.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
