### ISSUE TITLE
Auth time in the ID token

### ISSUE THREAD

**Issue by smogali** [google/google-oauth-java-client#119]
PyOIDC is generating id_tokens with the issued time with floating point precision. 
Ex: 1455192219.050872
This is generating an exception on the parse.

> > > java.lang.NumberFormatException: For input string:"1455192219.050872"
> > > open source implementation in python PyOIDC
> > > https://github.com/rohe/pyoidc/
> > > The spec says 'Number of Seconds'.  Is the value valid in this case?

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
