### ISSUE TITLE
StoredCredential Proguard Issue whe using FileDataStoreFactory

### ISSUE THREAD

**Issue by aglt** [google/google-oauth-java-client#120]
This line of code looks pretty harmless:
`public static final String DEFAULT_DATA_STORE_ID = StoredCredential.class.getSimpleName();`

But it is not if you are using Proguard (or Dexguard like in my case) for obfuscation. It will rename the StoredCredential class and as a result the DEFAULT_DATA_STORE_ID will change. There is no guaranty that the changed class name will be the same on each build so when you try to load the credentials from form the AuthorizationCodeFlow#loadCredentials the FileDataStoreFactory does not find them because of the name changes. And the user will have re-enter his credentials and a new file is created in the credentials directory. In my case users had to login on every upgrade of my app. 

Having the DEFAULT_DATA_STORE_ID as a String constant would solve this issue.
`public static final String DEFAULT_DATA_STORE_ID = "StoredCredential";`

The workaround is of course to tell Dexguard to keep this file (something like -keep class com.google.api.client.auth.oauth2.StoredCredential) and then the credential file name always has the same name: "StoredCredential", but this bug tricky to find, so for future users I would fix this.

```
public final class StoredCredential implements Serializable {

  /** Default data store ID. */
  public static final String DEFAULT_DATA_STORE_ID = StoredCredential.class.getSimpleName();
...
  /**
   * Returns the stored credential data store using the ID {@link #DEFAULT_DATA_STORE_ID}.
   *
   * @param dataStoreFactory data store factory
   * @return stored credential data store
   */
  public static DataStore<StoredCredential> getDefaultDataStore(DataStoreFactory dataStoreFactory)
      throws IOException {
    return dataStoreFactory.getDataStore(DEFAULT_DATA_STORE_ID);
  }
```

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
