### ISSUE TITLE
Mechanism to cancel waitForCode in LocalServerReceiver

### ISSUE THREAD

**Issue by chanseokoh** [google/google-oauth-java-client#127]
Currently, callers of `waitForCode()` are blocked and cannot escape the method until the server handles the login redirect. In IDEs, this is a critical problem, as users cannot cancel a login flow. Because of this, [Google Cloud Tools for IntelliJ](https://github.com/GoogleCloudPlatform/gcloud-intellij) already [duplicated the code](https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/master/google-account-plugin/src/com/google/cloud/tools/intellij/login/CancellableServerReceiver.java) of `LocalServerReceiver`. I may also duplicate the code soon for [Google Cloud Tools for Eclipse](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools).

One idea would be to make `stop()` (or a new method) escape a caller that is blocked or will be blocked on `waitForCode()`.

Another idea would be to make `waitForCode()` accept a timeout so that callers can poll.

**Comment by briandealwis** [comment]
> Another idea would be make waitForCode() accept a timeout so that callers can poll.

Or return a `Future`

**Comment by ejona86** [comment]
It looks like a bug that `stop()` does not cause `waitForCode()` to fail. That at the very least should be fixed. It would also be pretty easy to have a new `waittForCode(long, TimeUnit)` that also could throw `InterruptedException` (and probably `TimeoutException`).
