### ISSUE TITLE
Use "127.0.0.1" (IPv4) or "::1" (IPv6) instead of "localhost" in LocalServerReceiver

### ISSUE THREAD

**Issue by chanseokoh** [google/google-oauth-java-client#129]
I'm not an expert regarding this, but [Google Identity Platform recommends using "127.0.0.1" or "::1"](https://developers.google.com/identity/protocols/OAuth2InstalledApp):

> Note: It is also possible to use `localhost` in place of the loopback IP, but this may cause issues with client firewalls. Most firewalls allow loopback communication, though this may not always be the case.

**Comment by chanseokoh** [comment]
It is best to use [`InetAddress.getLoopbackAddress()`](https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getLoopbackAddress()) (note this doesn't throw any exception) to get an actual loopback address. (However, it requires Java 7.) Technically, it is always `::1` for an IPv6 address, and `127.*.*.*` (almost all the time `127.0.0.1`) for an IPv4 address.

Note that, `::1` (IPv6) should be enclosed in square brackets if used in a URL, e.g., `http://[::1]:12345`.

**Comment by chanseokoh** [comment]
Before Java 7, I think `InetAddress.getByName(null)` will return a loopback address according to the [JavaDoc](https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getByName(java.lang.String)). I actually looked into the JRE code, and it is indeed the case. This method declares that an exception can be thrown, but the exception is never thrown when getting a loopback address.

**Comment by marksnoopy** [comment]
There are something i can not understand. 

when i set the host valued "localhost" or "127.0.0.1" , the param "redirect_uri" of  the url  will be a local domain but not a network domain.  user click the "allow" buttuon , it will redirect to a local domin and display error.

https://accounts.google.com/o/oauth2/auth?client_id=xxxx&redirect_uri=http://localhost:9903/Callback&response_type=code&scope=https://www.googleapis.com/auth/drive%20email%20profile

```
 public String getRedirectUri() throws IOException {
    if (port == -1) {
      port = getUnusedPort();
    }
    server = new Server(port);
    for (Connector c : server.getConnectors()) {
      c.setHost(host);
    }
    server.addHandler(new CallbackHandler());
    try {
      server.start();
    } catch (Exception e) {
      Throwables.propagateIfPossible(e);
      throw new IOException(e);
    }
    return "http://" + host + ":" + port + CALLBACK_PATH;
  }
```

**Comment by chanseokoh** [comment]
Hi @marksnoopy,

I am not sure what is the actual error you're seeing, but it is correct that the redirect URI is a loopback address, i.e., any one of `127.0.0.0/8` such as `127.0.0.1` (or `localhost` which is not recommended). It is a web browser on your local machine that will make an HTTP request to your local web server (`LocalServerReciever` running on the same machine) through this redirect URI. Therefore, the redirect URL shouldn't be a network domain but a loopback address.

**Comment by marksnoopy** [comment]
@chanseokoh if the user visit the url from the internet but not the local machine  ?

**Comment by chanseokoh** [comment]
Yes, a user will visit the URL you posted above (https://accounts.google.com) for login, the remote login server will respond to his/her browser with the login result, and the browser will in turn connect to his/her local machine (the loopback redirect URI you see above).

**Comment by IOrlandoni** [comment]
But I was still at work. When I open EasyPhp I can not enter the address entered by typing  [http:// localhost or http://127.0.0.1](https://localhost.co/). The browser is warning that the page can not be displayed in the middle of these addresses. Where does the problem come from?

**Comment by chanseokoh** [comment]
@mattwhisenhunt I think this issue still stands. Originally, I thought I could simply replace "localhost" to "127.0.0.1" to simultaneously fix this issue while I was working on a seperate issue (https://github.com/google/google-oauth-java-client/pull/135). But I realized that [this might not cover IPv6](https://github.com/google/google-oauth-java-client/pull/135#r77667783) (not sure), and more crucially, I am no expert in this business, so I just decided to leave it as future work.

I have no permission to open the issue. Could you open it again?

**Comment by chingor13** [comment]
I'm going to close this issue as you currently can specify the hostname to bind to in the `LocalServerReceiver` constructor. This looks like it was added around the time the original bug.  The developer using `LocalServerReceiver` can choose which hostname to bind to.
