### ISSUE TITLE
Compile broken 

### ISSUE THREAD

**Issue by elharo** [google/google-oauth-java-client#131]
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

A simple mvn compile at the root on a fresh checkout fails:

ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.google.oauth-client:dailymotion-simple-cmdline-sample:[unknown-version] (/Users/elharo/google-oauth-java-client/samples/dailymotion-cmdline-sample/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.google.oauth-client:dailymotion-simple-cmdline-sample:[unknown-version]: Could not find artifact com.google.oauth-client:google-oauth-client-parent:pom:1.22.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by ejona86** [comment]
You have to `mvn install` the project first. The SNAPSHOT is a non-released version. At times we'll have SNAPSHOTS available, but they aren't strictly guaranteed and they may not match the version you are trying to compile with.

**Comment by elharo** [comment]
I don't follow. The sequence is 

1. git clone git@github.com:google/google-oauth-java-client.git
2. cd google-oauth-java-client
3. mvn compile

and this fails. Usually compile is a prerequisite for install, though I'm not a maven expert. If there's an extra step I'm missing somewhere, can we update the contributor instructions to include it?

**Comment by elharo** [comment]
I think the specific problem is that the samples from this repo specify 1.22.0-SNAPSHOT and should specify 1.23.0-SNAPSHOT to match the rest of the code in this repo.
