### ISSUE TITLE
$ mvn -q clirr:check broken

### ISSUE THREAD

**Issue by elharo** [google/google-oauth-java-client#133]
Fresh checkout from master. Both before and after fixing the compile:

Are the contribution instructions up to date?

elharo-macbookair2:google-oauth-java-client elharo$ mvn -q clirr:check
[ERROR] 4001: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Removed javax.jdo.spi.PersistenceCapable from the set of implemented interfaces
[ERROR] 6001: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Removed field jdoFlags
[ERROR] 6001: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Removed field jdoStateManager
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'protected OAuthHmacCredential()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public java.lang.Class ___jdo$loadClass(java.lang.String)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'protected int __jdoGetInheritedFieldCount()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'protected void jdoCopyField(com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential, int)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoCopyFields(java.lang.Object, int[])' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoCopyKeyFieldsFromObjectId(javax.jdo.spi.PersistenceCapable$ObjectIdFieldConsumer, java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'protected void jdoCopyKeyFieldsFromObjectId(java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoCopyKeyFieldsToObjectId(java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoCopyKeyFieldsToObjectId(javax.jdo.spi.PersistenceCapable$ObjectIdFieldSupplier, java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'protected int jdoGetManagedFieldCount()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public java.lang.Object jdoGetObjectId()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public javax.jdo.PersistenceManager jdoGetPersistenceManager()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public java.lang.Object jdoGetTransactionalObjectId()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public java.lang.Object jdoGetVersion()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public boolean jdoIsDeleted()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public boolean jdoIsDetached()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public boolean jdoIsDirty()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public boolean jdoIsNew()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public boolean jdoIsPersistent()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public boolean jdoIsTransactional()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoMakeDirty(java.lang.String)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public javax.jdo.spi.PersistenceCapable jdoNewInstance(javax.jdo.spi.StateManager)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public javax.jdo.spi.PersistenceCapable jdoNewInstance(javax.jdo.spi.StateManager, java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public java.lang.Object jdoNewObjectIdInstance()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public java.lang.Object jdoNewObjectIdInstance(java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'protected void jdoPreSerialize()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoProvideField(int)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoProvideFields(int[])' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoReplaceField(int)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoReplaceFields(int[])' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoReplaceFlags()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential: Method 'public void jdoReplaceStateManager(javax.jdo.spi.StateManager)' has been removed
[ERROR] 4001: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Removed javax.jdo.spi.PersistenceCapable from the set of implemented interfaces
[ERROR] 6001: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Removed field jdoFlags
[ERROR] 6001: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Removed field jdoStateManager
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'protected OAuthHmacThreeLeggedFlow()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public java.lang.Class ___jdo$loadClass(java.lang.String)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'protected int __jdoGetInheritedFieldCount()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'protected void jdoCopyField(com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow, int)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoCopyFields(java.lang.Object, int[])' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoCopyKeyFieldsFromObjectId(javax.jdo.spi.PersistenceCapable$ObjectIdFieldConsumer, java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'protected void jdoCopyKeyFieldsFromObjectId(java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoCopyKeyFieldsToObjectId(java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoCopyKeyFieldsToObjectId(javax.jdo.spi.PersistenceCapable$ObjectIdFieldSupplier, java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'protected int jdoGetManagedFieldCount()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public java.lang.Object jdoGetObjectId()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public javax.jdo.PersistenceManager jdoGetPersistenceManager()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public java.lang.Object jdoGetTransactionalObjectId()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public java.lang.Object jdoGetVersion()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public boolean jdoIsDeleted()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public boolean jdoIsDetached()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public boolean jdoIsDirty()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public boolean jdoIsNew()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public boolean jdoIsPersistent()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public boolean jdoIsTransactional()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoMakeDirty(java.lang.String)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public javax.jdo.spi.PersistenceCapable jdoNewInstance(javax.jdo.spi.StateManager)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public javax.jdo.spi.PersistenceCapable jdoNewInstance(javax.jdo.spi.StateManager, java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public java.lang.Object jdoNewObjectIdInstance()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public java.lang.Object jdoNewObjectIdInstance(java.lang.Object)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'protected void jdoPreSerialize()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoProvideField(int)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoProvideFields(int[])' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoReplaceField(int)' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoReplaceFields(int[])' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoReplaceFlags()' has been removed
[ERROR] 7002: com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow: Method 'public void jdoReplaceStateManager(javax.jdo.spi.StateManager)' has been removed
[ERROR] Failed to execute goal org.codehaus.mojo:clirr-maven-plugin:2.6:check (default-cli) on project google-oauth-client-servlet: There were 70 errors. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :google-oauth-client-servlet

**Comment by ejona86** [comment]
You can ignore clirr.
