### ISSUE TITLE
Logical issue in computeNonce() method from OAuthParameters class

### ISSUE THREAD

**Issue by petermalone** [google/google-oauth-java-client#142]
The computeNonce() suffers from a logical error. As per the method comments, the method "Computes a nonce based on the hex string of a random non-negative long"

The method is as follows:
nonce = Long.toHexString(Math.abs(RANDOM.nextLong()));

RANDOM is defined as a SecureRandom object, and the SecureRandom.nextLong() calls Random.nextLong() which can return positive and negative numbers. 

As per squid:S267 Long.MIN_VALUE could be returned from Random.nextLong(). Calling Math.abs on values returned from these methods is ill-advised.

The problem is that Random.nextLong() can return Long.MIN_VALUE. Due to two's complement representation, the absolute value of Long.MIN_VALUE is itself, the most negative possible long.

My solution is to remove the Math.abs() call and do some shifting, so that we are dealing with positive numbers only - as per the comments of the method.

nonce = Long.toHexString(RANDOM.nextLong() >>> 1);

Apologies for the double commit for this fix.

**Comment by chingor13** [comment]
Sorry for the long delay getting to this.

Would you like to submit your changes as a PR?

**Comment by petermalone** [comment]
Oh wow haha. I forgot completely about this. Yeah let me open a pull request when I'm back at my computer. Should be in less than 2 hours.

**Comment by petermalone** [comment]
I was able to do it quicker than expected. Should be referenced above but here you go: https://github.com/google/google-oauth-java-client/pull/181

If you don't like the format please let me know.

**Comment by chingor13** [comment]
After further consideration, the actual long value and positivity/negativity of the nonce doesn't matter - [it's a random string](https://oauth.net/core/1.0a/#nonce) that is used once. Bitshifting does force the number to be positive but also reduces the number of bits of entropy by 1.

The current implementation can produce `0000000000000000` to `ffffffffffffffff` as the ranges `Long.MIN_VALUE` (`8000000000000000`) to `-1` (`ffffffffffffffff`) and `0` (`0000000000000000`) to `Long.MAX_VALUE` (`7fffffffffffffff`).

If anything, it looks like we can remove the `Math.abs`.
