### ISSUE TITLE
400 HTTP error when permissions screen remains open for an hour or so.

### ISSUE THREAD

**Issue by nemo347** [google/google-oauth-java-client#143]
When permissions screen has been displayed for an hour or so and Allow/Deny are pressed I get:
400. That’s an error.
Unverified state_wrapper. That’s all we know.

Both buttons work fine when press within a normal time frame.
I assume the token has expired but how do you handle this error? 

**Details:**
Client version: com.google.apis:google-api-services-oauth2:v2-rev106-1.21.0
access_type=offline&approval_prompt=force
redirect method.

**Comment by chingor13** [comment]
This appears to have been an unhandled credentials expiry that has since been fixed. Closing this out, but if it is still happening, feel free to reopen with additional information.
