### ISSUE TITLE
Servlet API 2.5 is a compile dependency that breaks web apps

### ISSUE THREAD

**Issue by meltsufin** [google/google-oauth-java-client#145]
The Servlet API should not be included as a compile dependency in google-oauth-client-appengine because it breaks applications that depend on a different version of the Servlet API.

For example, if you try adding the library to https://github.com/spring-guides/gs-spring-boot, the application will fail at startup.

**Comment by meltsufin** [comment]
@garrettjonesgoogle Have you had a chance to look at this?

**Comment by garrettjonesgoogle** [comment]
I have not.

**Comment by rdayal** [comment]
ping - any updates?

**Comment by garrettjonesgoogle** [comment]
It's a blocking issue for the GA release of google-cloud-java, so we should get to it soon.

**Comment by garrettjonesgoogle** [comment]
So I looked at the code in `google-oauth-client-appengine`, and it appears that the entire point of the module is to provide servlets that extend `servlet-api`, and thus it is tightly coupled with `servlet-api` at compile time. Thus, the dependency can't just be removed - the whole module would have to be rewritten in a breaking way to support some new kind of model. 

I'm assuming that spring-boot depends on an incompatible version of servlet-api. Is that the case, or is there another problem?

**Comment by lesv** [comment]
https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client-appengine/pom.xml
Should be:
`<scope>provided</scope>`

In a normal Servlet environment, this is always provided.

**Comment by lesv** [comment]
Also https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client-servlet/pom.xml#L100-L103
Should be: `<scope>provided</scope>`

**Comment by meltsufin** [comment]
@garrettjonesgoogle I don't think you need to remove the dependency. Just set the scope to `provided`. The code should still compile.

**Comment by lesv** [comment]
This has been released.
