### ISSUE TITLE
Let LocalServerReceiver.getRedirectUrl() return actual host Jetty decided to use

### ISSUE THREAD

**Issue by chanseokoh** [google/google-oauth-java-client#158]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2148#issuecomment-315433992

`getRedirectUrl()` always returns `localhost`, but in the above issue, the actual address bound by Jetty was `192.168.*.*`.

The code below should `return "http://" + connector.getHost() + ":" + port + callbackPath;`.

https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java#L129

```java
  public String getRedirectUri() throws IOException {
    server = new Server(port != -1 ? port : 0);
    Connector connector = server.getConnectors()[0];
    connector.setHost(host);
    server.addHandler(new CallbackHandler());
    try {
      server.start();
      port = connector.getLocalPort();
     } catch (Exception e) {
      Throwables.propagateIfPossible(e);
      throw new IOException(e);
    }
    return "http://" + host + ":" + port + callbackPath;
  }
```

**Comment by chanseokoh** [comment]
Seems like the above commits were the fix. I wonder why this issue wasn't auto-closed.

**Comment by mattwhisenhunt** [comment]
I don't think it has been merged yet.
https://github.com/google/google-oauth-java-client/pull/173

**Comment by chanseokoh** [comment]
I believe #173 fixed the issue.
