### ISSUE TITLE
Release notes from version 1.18.0-rc

### ISSUE THREAD

**Issue by kiru** [google/google-oauth-java-client#160]
Hello, 

Where do I find the release later than 1.18-0-rc ?
The last one here is from 2014: https://developers.google.com/api-client-library/java/google-oauth-java-client/release-notes

Thank you, 
Kiru

**Comment by mattwhisenhunt** [comment]
This library is in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. As such there wouldn't be much to tell in such notes.

To see everything that is changed in a given release you can use the version tags to craft a custom URL:
https://github.com/google/google-oauth-java-client/compare/1.22.0...1.23.0

**Comment by mattwhisenhunt** [comment]
Closing for now. Please feel free to reopen if your question isn't answer sufficiently.

**Comment by kiru** [comment]
Hello @mattwhisenhunt 
Thank you for the reply. I see that this library is in maintenance mode, is it possible to mention that at least in the README or on https://developers.google.com/api-client-library/java/google-oauth-java-client/release-notes ?

Thanks, 
Kiru
