### ISSUE TITLE
The SHA-1 Message Digest in the Archive Comment Appears to Be Incorrect

### ISSUE THREAD

**Issue by txwizard** [google/google-oauth-java-client#163]
Since I can't find a known good copy that is accessible to Maven, elected to download the project from here. When I opened the archive, my copy of WinZip displayed the comment, which contains "2ce0fb70492af785545082d0190fadd5daf4db9f" - obviously a SHA-1 message digest.  However, when I compute SHA-1 digest of the downloaded file, I get "2ce0fb70492af785545082d0190fadd5daf4db9f" - clearly different.

This situation makes me reluctant to trust the integrity of the archive, and calls into question the trustworthiness of the entire OAuth project. Please advise at your earliest convenience.

Thank you!

**Comment by txwizard** [comment]
I eventually found my way to the correct Maven repository artifact, thanks to information that I found further down the main project page. That doesn't negate in any way my concern about the incorrect SHA-1 hash embedded in the comment of the generated ZIP archive.

**Comment by mattwhisenhunt** [comment]
Thanks for the heads up.
