### ISSUE TITLE
Unable to open browser warning

### ISSUE THREAD

**Issue by dannygonzalez** [google/google-oauth-java-client#174]
Using v1.23.0

AuthorizationCodeInstalledApp.browse can fail when trying to open a browser on Windows if no default browser has been set.

Look at [line 133](https://github.com/google/google-oauth-java-client/blob/e848c78e656517df32f22a1b94cd9b615174a9d6/google-oauth-client-java6/src/main/java/com/google/api/client/extensions/java6/auth/oauth2/AuthorizationCodeInstalledApp.java#L133). 

This results in our code hanging due to the google analytics api that uses this library for authentication never to return back to us.

**Comment by chingor13** [comment]
Thanks for filing this issue. 

#182 introduces an `AuthorizationCodeInstalledApp.Browser` interface which will let you customize the browse behavior. The `DefaultBrowser` (current behavior) swallows the thrown `IOException` when no browser is set and there's no exception to handle.

With #182, you would be able to write a `Browser` that doesn't swallow the exception and can be handled elsewhere.

Would this address your issue?

**Comment by chingor13** [comment]
[1.25.0 is released](https://github.com/google/google-oauth-java-client/releases/tag/1.25.0) with the ability to customize the browse behavior.
