### ISSUE TITLE
[ReOpen]hard coded private static final String CALLBACK_PATH = "/Callback" in LocalServerReceiver.java #108

### ISSUE THREAD

**Issue by FutureGadget** [google/google-oauth-java-client#196]
This issue was mentioned in the following link: https://github.com/google/google-oauth-java-client/issues/108.

Currently (com.google.oauth-client:google-oauth-client-jetty:1.23.0) not resolved.

**Comment by chingor13** [comment]
This is addressed in #171 and will be included in 1.25.0

**Comment by chingor13** [comment]
1.25.0 is [released](https://github.com/google/google-oauth-java-client/releases/tag/1.25.0).
