### ISSUE TITLE
OAuth 2.0 Token Revocation

### ISSUE THREAD

**Issue by wonderfly** [google/google-oauth-java-client#20]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on December 09, 2011 12:34:53_

External references, such as a standards document, or specification? http://tools.ietf.org/html/draft-lodderstedt-oauth-revocation Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? All Please describe the feature requested. Implement the specification for OAuth 2.0 Token Revocation.  Example HTTP request:

```
    POST /revoke HTTP/1.1
    Host: server.example.com
    Content-Type: application/x-www-form-urlencoded
    Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

    token=45ghiukldjahdnhzdauz&
```

_Original issue: http://code.google.com/p/google-oauth-java-client/issues/detail?id=20_

**Comment by GuiSim** [comment]
Why was this closed :( There's still no clean way to revoke a token using the Google Java SDK

**Comment by JustinBeckwith** [comment]
Greetings!  Would you mind opening up a new feature request?  A lot of these bugs were so old we couldn't even tell where they came from or if they were still a problem.

**Comment by GuiSim** [comment]
@JustinBeckwith Okay! I'll do that 👇 
https://github.com/googleapis/google-oauth-java-client/issues/250
