### ISSUE TITLE
violation of OAuth 1.0 spec (repeated query parameters)

### ISSUE THREAD

**Issue by wonderfly** [google/google-oauth-java-client#36]
_From [magib...@gmail.com](https://code.google.com/u/101131741510052571593/) on April 26, 2012 07:34:00_

Version of google-oauth-java-client (e.g. 1.5.0-beta)? 1.8.0-beta, 1.9.0-beta-SNAPSHOT Java environment (e.g. Java 6, Android 2.3, App Engine)? All? Describe the problem. OAuth 1.0 OAuthParameters class overwrites repeated query parameters instead of sorting by value, as required by the OAuth 1.0 spec ( http://tools.ietf.org/html/rfc5849#section-3.4.1.3.2 , second part of point 2). How would you expect it to be fixed? The overwriting happens in lines 154-156 of com.google.api.client.auth.oauth.OAuthParameters.  One way to fix would be to change <code>parameters</code> (declared on line 139) from TreeMap<String, String> to TreeMap<String, Object>, where the value could be a String or a TreeSet<String>.  This would be analogous to the handling of repeated query parameters in GenericUrl.  Corresponding adjustment to the putParameter() method and the building of the normalizedParameters String should complete the fix.

_Original issue: http://code.google.com/p/google-oauth-java-client/issues/detail?id=36_

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
