### ISSUE TITLE
Token-Request flow is not working when using Google "high-level" classes

### ISSUE THREAD

**Issue by wonderfly** [google/google-oauth-java-client#59]
_From [Oh...@watchdox.com](https://code.google.com/u/116128294064745302567/) on November 07, 2012 00:27:31_

Version of google-oauth-java-client (e.g. 1.5.0-beta)?
1.12.0-beta 

Java environment (e.g. Java 6, Android 2.3, App Engine)? 
Java 6 

Describe the problem. 
In case that I wanna use the "high-level" classes, such as AuthorizationCodeFlow and TokenRequest, the token-request flow is not working.
I was trying to run the example here ( https://code.google.com/p/google-oauth-java-client/wiki/OAuth2 - the main Wiki page), and the code is wrong from several reason:
1. authorize flow: the code is not running since I get exception that SCOPES is missing. So I've added "scope" to my request by                         .setScopes("read")
2. token-request: 
2.a. same error on the scopes, even though when asking for a token there should be no scope in the request.
2.b. the client-id and client-secret are not passed in the request, so I keep getting "400: invalid-request" How would you expect it to be fixed? fixes need to be done in the high-level classes such AbstractAuthorizationCodeServlet, AbstractAuthorizationCodeCallbackServlet
and most important: TokenRequest must be fixed so the client-id and client-secret will be passed in the request, and omit "scope" from the request.

_Original issue: http://code.google.com/p/google-oauth-java-client/issues/detail?id=59_

**Comment by nitinsinghit** [comment]
@wonderfly How I request for ID_TOKEN after getting access token from using AbstractAuthorizationCodeServlet, AbstractAuthorizationCodeCallbackServlet?

**Comment by wonderfly** [comment]
I imported these old issues from another issue tracker with my own credentials so all comments have me as the owner. But please note that the first line of every comment points to the original author.

Anyway, you can ping @ejona or @anthmgoogle on auth related questions.

**Comment by nitinsinghit** [comment]
@ejona86 @anthmgoogle  How I request for ID_TOKEN after getting access token from using AbstractAuthorizationCodeServlet, AbstractAuthorizationCodeCallbackServlet?

**Comment by chingor13** [comment]
The original issue seems like a documentation gap on setting scopes and using `AuthorizationCodeFlow`.

@nitinsinghit's added issue is a question on how to use the OpenID token which I've opened #188.

**Comment by chingor13** [comment]
I can no longer find any Google examples that are missing the `setScopes` call when setting up an `AuthorizationCodeFlow`
