### ISSUE TITLE
NPE in AuthorizationCodeInstalledApp when Credential Expires Not Set

### ISSUE THREAD

**Issue by wonderfly** [google/google-oauth-java-client#90]
_From [jakewhar...@gmail.com](https://code.google.com/u/108284392618554783657/) on February 24, 2014 10:10:30_

Version of google-oauth-java-client (e.g. 1.5.0-beta)? 1.17-rc Java environment (e.g. Java 6, Android 2.3, App Engine)? Java 1.8.0-b129
OSX 10.8.5 Describe the problem. AuthorizationCodeInstalledApp contains the code "credential.getExpiresInSeconds() > 60" on line 72. The documentation for Credential#getExpiresInSections specifies that it will return null when unset, however.

This causes an NPE. How would you expect it to be fixed? Null check before implicitly casting to long.

_Original issue: http://code.google.com/p/google-oauth-java-client/issues/detail?id=90_

**Comment by JBartlett86** [comment]
Hi,
Is there any expectation to fix this issue?
I am trying to use with the Slack API which doesn't return an expiry period as part of its authentication which causes this bug.

**Comment by chingor13** [comment]
This was fixed in #144 and has been available since 1.23.0
